common: &common
  adapter: postgresql
  username: tyler
  password: 123456

development:
  <<: *common
  database: sample_app_dev

test: &test
  <<: *common
  database: sample_app_test

cucumber:
  <<: *test